//Localhost ###
http://localhost:3000/contacts
http://localhost:3000/contact?id=626c1be05924bf7a3d33dd56
http://localhost:3000/contact?id=626c1c215924bf7a3d33dd57
http://localhost:3000/contact?id=626c1c485924bf7a3d33dd58

(DELETE) http://localhost:3000/contact?id=627695401fb480145393b829
(POST) http://localhost:3000/contact
{
    "_id": "627695401fb480145393b829",
    "firstName": "Trent",
    "lastName": "Weber",
    "email": "weber@gmail.com",
    "favoriteColor": "blue",
    "birthday": "7/12/98"
}
(PUT) http://localhost:3000/contact
{
    "id": "626c1c485924bf7a3d33dd58",
    "firstName": "DaKun",
    "lastName": "Wang",
    "email": "xhc175892@gmail.com",
    "favoriteColor": "white",
    "birthday": "10/05/98"
}

//Production Deployed ###
https://safe-fjord-75598.herokuapp.com/contacts
https://safe-fjord-75598.herokuapp.com/contact?id=626c1be05924bf7a3d33dd56
https://safe-fjord-75598.herokuapp.com/contact?id=626c1c215924bf7a3d33dd57
https://safe-fjord-75598.herokuapp.com/contact?id=626c1c485924bf7a3d33dd58

(POST) https://safe-fjord-75598.herokuapp.com/contact
{
    "firstName": "George",
    "lastName": "Orwell",
    "email": "wellian@gmail.com",
    "favoriteColor": "purple",
    "birthday": "7/12/83"
}
(PUT) https://safe-fjord-75598.herokuapp.com/contact
{
    "id": "626c1c485924bf7a3d33dd58",
    "firstName": "DaKun",
    "lastName": "Wang",
    "email": "xhc175892@gmail.com",
    "favoriteColor": "orange",
    "birthday": "10/05/98"
}
(DELETE) https://safe-fjord-75598.herokuapp.com/contact?id=627696d5a43796c4b728d763